version: '3.8'

services:
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/default.conf:/etc/nginx/default.conf:ro
      - ./frontend/static:/usr/share/nginx/html:ro
    # ports: # Các service dùng port nội bộ nên không cần map
    #   - "8080:80"
    networks:
      - webnet

  backend:
    build: ./backend
    image: flask_backend
    container_name: flask_app
    restart: always
    expose:
      - "5000"
    networks:
      - webnet

  gateway:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./gateway/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./certbot/www:/var/www/certbot/www
      - ./certbot/conf:/etc/letsencrypt
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - frontend
      - backend
    networks:
      - webnet

networks:
  webnet:
